"""add indexes

Revision ID: 01892cd3c70e
Revises: 1567a45ceb10
Create Date: 2026-04-20 18:38:34.498565

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "01892cd3c70e"
down_revision: Union[str, Sequence[str], None] = "1567a45ceb10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("events", "space_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("events", "event_type", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "events",
        "payload",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "events", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.create_index(op.f("ix_events_space_id"), "events", ["space_id"], unique=False)
    op.alter_column("space_members", "role", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "space_members",
        "joined_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column("spaces", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("spaces", "invite_code", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "spaces", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column("tasks", "space_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("tasks", "title", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("tasks", "is_recurring", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("tasks", "status", existing_type=sa.VARCHAR(), nullable=False)
    op.create_index(op.f("ix_tasks_space_id"), "tasks", ["space_id"], unique=False)
    op.alter_column("users", "login", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "users", "password_hash", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "users", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column("users", "password_hash", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "login", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_index(op.f("ix_tasks_space_id"), table_name="tasks")
    op.alter_column("tasks", "status", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("tasks", "is_recurring", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("tasks", "title", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("tasks", "space_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "spaces", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column("spaces", "invite_code", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("spaces", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "space_members",
        "joined_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column("space_members", "role", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_index(op.f("ix_events_space_id"), table_name="events")
    op.alter_column(
        "events", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "events",
        "payload",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column("events", "event_type", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("events", "space_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
