"""rename username and login_name

Revision ID: 43ba49e1c00f
Revises: 7979daf71c08
Create Date: 2026-03-18 21:38:25.424322

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "43ba49e1c00f"
down_revision: Union[str, Sequence[str], None] = "7979daf71c08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("login", sa.String(), nullable=True))
    op.add_column("users", sa.Column("name", sa.String(), nullable=True))
    op.drop_index(op.f("ix_users_login_name"), table_name="users")
    op.create_index(op.f("ix_users_login"), "users", ["login"], unique=True)
    op.drop_column("users", "login_name")
    op.drop_column("users", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "users",
        sa.Column("login_name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_users_login"), table_name="users")
    op.create_index(op.f("ix_users_login_name"), "users", ["login_name"], unique=True)
    op.drop_column("users", "name")
    op.drop_column("users", "login")
    # ### end Alembic commands ###
